import React from 'react';
import {
  Html,
  Head,
  Body,
  Container,
  Section,
  Text,
  Heading,
  Hr,
  Link,
  Img,
  Preview,
} from '@react-email/components';
import { DetailedFeedbackReport } from '../types';

interface ClerkReportEmailProps {
  report: DetailedFeedbackReport;
}

export const ClerkReportEmail: React.FC<ClerkReportEmailProps> = ({ report }) => {
  return (
    <Html>
      <Head />
      <Preview>Your ClerkSmart Case Report: {report.diagnosis}</Preview>
      <Body style={styles.body}>
        <Container style={styles.container}>
          <Heading style={styles.header}>ClerkSmart Case Report</Heading>
          
          <Section style={styles.section}>
            <Heading as="h2" style={styles.sectionHeading}>Case Diagnosis</Heading>
            <Text style={styles.text}>{report.diagnosis}</Text>
          </Section>
          
          <Hr style={styles.divider} />
          
          <Section style={styles.section}>
            <Heading as="h2" style={styles.sectionHeading}>Key Takeaway</Heading>
            <Text style={styles.text}>{report.keyTakeaway}</Text>
          </Section>
          
          <Section style={styles.section}>
            <Heading as="h2" style={styles.sectionHeading}>What You Did Well</Heading>
            <ul style={styles.list}>
              {report.whatYouDidWell.map((point, index) => (
                <li key={index} style={styles.listItem}>
                  <Text style={styles.text}>{point}</Text>
                </li>
              ))}
            </ul>
          </Section>
          
          <Section style={styles.section}>
            <Heading as="h2" style={styles.sectionHeading}>Areas for Improvement</Heading>
            <ul style={styles.list}>
              {report.whatCouldBeImproved.map((point, index) => (
                <li key={index} style={styles.listItem}>
                  <Text style={styles.text}>{point}</Text>
                </li>
              ))}
            </ul>
          </Section>
          
          <Hr style={styles.divider} />
          
          <Section style={styles.section}>
            <Heading as="h2" style={styles.sectionHeading}>In-depth Analysis</Heading>
            
            <Heading as="h3" style={styles.subHeading}>Highlights from your conversation:</Heading>
            {report.positiveQuotes.map((quote, index) => (
              <div key={index} style={styles.quoteContainer}>
                <Text style={styles.quote}>"{quote.quote}"</Text>
                <Text style={styles.quoteExplanation}><strong>Analysis:</strong> {quote.explanation}</Text>
              </div>
            ))}
            
            <Heading as="h3" style={styles.subHeading}>Learning opportunities from your conversation:</Heading>
            {report.improvementQuotes.map((quote, index) => (
              <div key={index} style={styles.quoteContainer}>
                <Text style={styles.quote}>"{quote.quote}"</Text>
                <Text style={styles.quoteExplanation}><strong>Analysis:</strong> {quote.explanation}</Text>
              </div>
            ))}
          </Section>
          
          <Hr style={styles.divider} />
          
          <Section style={styles.section}>
            <Heading as="h2" style={styles.sectionHeading}>Clinical Tip</Heading>
            <Text style={styles.text}>{report.clinicalTip}</Text>
          </Section>
          
          <Hr style={styles.divider} />
          
          <Section style={styles.footer}>
            <Text style={styles.footerText}>
              This report was generated by ClerkSmart to help you improve your clinical skills.
            </Text>
            <Text style={styles.footerText}>
              © {new Date().getFullYear()} ClerkSmart
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
};

const styles = {
  body: {
    backgroundColor: '#f6f9fc',
    fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  container: {
    margin: '0 auto',
    padding: '20px 0',
    maxWidth: '600px',
  },
  header: {
    fontSize: '24px',
    lineHeight: '1.3',
    fontWeight: '700',
    color: '#0f766e',
    textAlign: 'center' as const,
    padding: '15px 0',
  },
  section: {
    padding: '15px 0',
  },
  sectionHeading: {
    fontSize: '18px',
    lineHeight: '1.3',
    fontWeight: '600',
    color: '#0f766e',
    margin: '10px 0',
  },
  subHeading: {
    fontSize: '16px',
    lineHeight: '1.3',
    fontWeight: '600',
    color: '#0f766e',
    margin: '15px 0 10px 0',
  },
  text: {
    fontSize: '14px',
    lineHeight: '1.6',
    color: '#334155',
    margin: '8px 0',
  },
  divider: {
    borderTop: '1px solid #e2e8f0',
    margin: '15px 0',
  },
  list: {
    padding: '0 0 0 20px',
    margin: '10px 0',
  },
  listItem: {
    margin: '5px 0',
  },
  quoteContainer: {
    backgroundColor: '#f8fafc',
    borderLeft: '3px solid #0f766e',
    padding: '10px 15px',
    margin: '15px 0',
  },
  quote: {
    fontSize: '14px',
    fontStyle: 'italic',
    color: '#334155',
    margin: '0 0 8px 0',
  },
  quoteExplanation: {
    fontSize: '13px',
    color: '#475569',
    margin: '0',
  },
  footer: {
    textAlign: 'center' as const,
    padding: '15px 0',
  },
  footerText: {
    fontSize: '12px',
    color: '#64748b',
    margin: '5px 0',
  },
};

export default ClerkReportEmail; 